### ISSUE TITLE
Energi3-aarch64-installer.sh not supported Raspberry Pi4

### ISSUE THREAD

**Issue by FCU4ever** [energicryptocurrency/energi3-provisioning#1]
When I use 

bash -ic "$(wget -4qO- -o- raw.githubusercontent.com/energicryptocurrency/energi3-provisioning/master/scripts/linux/energi3-aarch64-installer.sh)" ; source ~/.bashrc

I've got the message: Raspbian GNU/Linux 10 is not supported.

Ho do I get the energi3 working on my Raspberry Pi 4.

**Comment by andvgal** [comment]
Please contact our support via available methods: https://docs.energi.software/en/support/help-me

GitHub is not covered by Support unfortunately.
